id: PAAA5AF1F
initial_creation_type: input
source_metadata:
  title: Tsok Series
  language: zh
  description: 'Lotsawa House presents the following texts related to the practice
    of tsok (tshogs) or feast-gathering (Skt. gaṇacakra):'
  volume:
    da7c25c81324467f9dcfe20da52cd250:
      title: Introduction to Gaṇacakra (Tsok)
      parent: Introduction
    89c757b49039417197c9f5c5d4d6092b:
      title: A Concise Explanation of Gaṇacakra
      parent: Explanation
    fb81ad2f3c754756b62a07cb2b035cdf:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Explanation
    8ae3d594276b420e925bf29a48112141:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Explanation
    216e6e0de94e43c69a3eb54675803f89:
      title: The Gaṇacakra Ritual
      parent: Explanation
    4cb0747b13734697bac2b89faf87149e:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Explanation
    d19baff6f7d842218705ff5a5601748a:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Offering Liturgies
    691986115129490ab82bdc064c5cbef5:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Offering Liturgies
    015c1503ea7c4767808cc0c306bc559d:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Prayers
    8741829d388b4b0f821861fe57f92da9:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Prayers
    d7eab16f393d4d4ebbe3c5be6c942ed3:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Prayers
    0e43a61fdc6249d9a2136400f75ea763:
      title: Brief Prayer of the Feast Gathering
      parent: Prayers
    9427c76bfd26432aa639c064719f346b:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
    fd340ee273074d998220d76adc10f8ff:
      title: Food Offering Prayer
      parent: Prayers
    430d39852b684e8b83c03be3c9949b1d:
      title: Concise Tsok Feast
      parent: Prayers
    ecd4ac294d584f6eb6852da21c892a47:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Prayers
    840de74b9e804e15becaee02ee1fe826:
      title: A Concise Feast Prayer
      parent: Prayers
    14de8f13ebca4c0eb0e19bb1aa47a4e9:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Remainder Offering
    c6196ff3653e4b64a3e26152fce1a392:
      title: The Song of the Vajra
      parent: Songs
    1affeb788c3e42958f2e1aa7a0653d06:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Songs
    c902dd12010b4672a7d78761cc3d8925:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Songs
    19525c5ee9fc4ee4901681c55868fe33:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Songs
    6fa2868cb89f470d894f1b01d55b0c63:
      title: Song of the Feast (Tsok Lu)
      parent: Songs
created_at: '2022-03-01T06:26:39.649252'
last_modified_at: '2022-03-01T06:26:39.649254'
